# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'comment'), (2, 'post')])),
                ('fb_id', models.CharField(max_length=50)),
                ('fb_user_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('posted_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'awaiting_edit'), (3, 'deleted'), (4, 'approved')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postments', to='moderations.FBGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='moderation',
            name='group',
        ),
        migrations.AddField(
            model_name='action',
            name='preformed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 11, 7, 25, 334215)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='preformed_by',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderations.Moderator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(1, 'filtered'), (2, 'viewed'), (3, 'requested_edit'), (4, 'approved'), (5, 'removed'), (6, 'blocked')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moderator',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.AddField(
            model_name='action',
            name='postment',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderations.Postment'),
            preserve_default=False,
        ),
    ]
