# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0003_auto_20160627_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbgroup',
            name='hate_words',
            field=models.TextField(default='זונה;נאצי;בוגד;פאשיסט'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postment',
            name='num_reactions',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postment',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderations.Postment'),
        ),
    ]
