# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0004_auto_20160627_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postment',
            name='num_reactions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderations.Postment'),
        ),
    ]
