# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0005_auto_20160627_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='preformed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderations.Moderator'),
        ),
    ]
