# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0006_auto_20160630_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='preformed_at',
            new_name='performed_at',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='preformed_by',
            new_name='performed_by',
        ),
    ]
